export {
  default as PrayersReducer,
  getPrayers,
  getPrayersSuccess,
  getPrayersFailed,
  addPrayer,
  addPrayerFailed,
  addPrayerSuccess,
  updatePrayer,
  updatePrayerFailed,
  updatePrayerSuccess,
  deletePrayer,
  deletePrayerFailed,
  deletePrayerSuccess,
} from './PrayersSlice';
